version: '3.7'
services:
  live-view-counter:
    image: live-view-counter
    restart: unless-stopped
    depends_on:
      live-view-counter-boostrap:
        condition: service_completed_successfully
    ports:
      - 3001:3000
    environment: &env
      - APP_URL=http://127.0.0.1:3001
      - DB_HOST=mysql8
      - DB_PORT=3306
      - DB_DATABASE=liveviewcounter
      - DB_USERNAME=liveviewcounter
      - DB_PASSWORD=liveviewcounter
  live-view-counter-boostrap:
    image: live-view-counter
    depends_on:
      - mysql8
    environment: *env
    command: bash -c 'ls; bin/wait-mysql && bin/migrate latest'
  mysql8:
    image: mysql:8.4.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=liveviewcounter
      - MYSQL_USER=liveviewcounter
      - MYSQL_PASSWORD=liveviewcounter
